---
- name: Install Docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
  vars:
    docker_packages: "{{ ['docker.io', 'docker-compose-v2'] if ansible_facts.os_family == 'Debian' else ['docker', 'docker-compose-plugin'] }}"
- name: Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
- name: Add users to Docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
