---
- name: Install Linux auditing
  hosts: linux
  become: true
  tasks:
    - name: Install audit daemon
      ansible.builtin.package:
        name: audit
        state: present
    - name: Enable audit daemon
      ansible.builtin.service:
        name: auditd
        state: started
        enabled: true

