---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: backups-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    command: '/bin/sh -c "while sleep 3600; do :; done"'
    cgroupns_mode: private
    network_mode: host
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
verifier:
  name: ansible
